name: Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: '0.1.1'
        required: false
        type: boolean

jobs:
  versioning_new:
    name: Versioning_new
    runs-on: ubuntu-latest
    outputs:
      version_output: ${{ steps.current_version.outputs.prev_version_output }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: Get current version
        id: current_version
        run: |
          output=$(python src/subsearch/data/version.py --get-version)
          echo "{prev_version_output}={$output}" >> $GITHUB_OUTPUT

      - name: Update version.py
        run: echo ${{ github.ref_name }}

      - name: Push new version
        run: |
          echo "Bump version: v${{steps.current_version.outputs.prev_version_output}} → ${{ github.ref_name }}"

