name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - uses: actions/setup-python@v4
        with:
          python-version: "*"
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          configuration: .github/configs/changelog_builder.json
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Something
        id: new_changelog
        run: |
          echo "${{steps.github_release.outputs.changelog}}" > tmp_changelog.md
          python scripts/reformat_changelog.py
          echo "::set-output name=changelog::$(cat tmp_changelog.md)"

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.new_changelog.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: |
            tmp_changelog.txt
