name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    name: Build and Publish
    needs: versioning
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          configuration: .github/configs/changelog_builder.json
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
